### ISSUE TITLE
KVM Motioning issue

### ISSUE THREAD

**Issue by techidee** [sergiotocalini/virbix#10]
Hi,

I have installed KVM virbix as per your instructions, but we are getting the error below, please help me to resolve its issue.

**Cannot create item: item with the same key "virbix[domain_check, {#DOMUUID}, state]" already exists.
Cannot create item: item with the same key "virbix[net_check, {#NETUUID}, active]" already exists.
Cannot create item: item with the same key "virbix[pool_check, {#POOLUUID}, size_free]" already exists.
Cannot create item: item with the same key "virbix[pool_check, {#POOLUUID}, size_used]" already exists.
Cannot create item: item with the same key "virbix[pool_check, {#POOLUUID}, state]" already exists.**

I set the sudo access as suggested but the issue is the same.

Thanks
Pradeep

**Comment by sergiotocalini** [comment]
Hi @pspal83,

Sorry for the delay, I hope this could be solved from your side, but it seems that it is an issue with your virsh command.
Let me know if there is a still an issue.

Regards,
Sergio

**Comment by mcirrici** [comment]
Hi,

I am also seeing the same issues after the sudo workaround, where Zabbix cannot create the item stating that the item already exists.

Anything else I need to check?

Thanks,
-Matt

**Comment by sergiotocalini** [comment]
Hi @mcirrici,
Thanks for your comment.
Can you please share the following commands from the zabbix server?

~# agenthost="kvm-server" # change this agenthost with your kvm server name or ip
~# zabbix-get -s "${agenthost}" -k "virbix.discovery[domain_list, DOMID:DOMNAME:DOMUUID:DOMTYPE:DOMSTATE]"
~# zabbix-get -s "${agenthost}" -k "virbix.discovery[net_list, NETNAME:NETUUID:NETACTIVE:NETBRIDGE]"
~# zabbix-get -s "${agenthost}" -k "virbix.discovery[pool_list, POOLNAME:POOLUUID:POOLSTATE]"

Probably there is a missing configuration around your agent.
Looking forward to hearing from you.

Regards,
Sergio

**Comment by mcirrici** [comment]
Hi Sergio,

Each command returns empty data, such as

         zabbix_get -s "${agenthost}" -k "virbix.discovery[domain_list, DOMID:DOMNAME:DOMUUID:DOMTYPE:DOMSTATE]"
{
                 "data":[
                       {  }
                 ]
}

Looking forward to hearing back. Thanks in advance!

**Comment by sergiotocalini** [comment]
Hi @mcirrici,

Thanks for your comment.
There is an issue with your script that is not returning data from the zabbix-agent. I've just introduced a change on the script that will prevent the error message on the zabbix-server. On the other hand, you will need to fix this issue on the zabbix agent host, probably there is a permission issue. Please ensure that on the zabbix-agent host the user zabbix is allow to run command with sudo.
Looking forward to hearing from you.

Regards,
Sergio
