### ISSUE TITLE
Zabbix v5 compatability

### ISSUE THREAD

**Issue by viktorix** [sergiotocalini/virbix#11]
Hi, is v5 supported? We can't seem to get it working with v5.0.1. When we try to run virbix.sh manually, we get ZBX_NOTSUPPORTED.

**Comment by sergiotocalini** [comment]
Hi @viktorix 
Thanks for your comment.
The script is not fixed to any zabbix version so it is not a problem related with the zabbix version.
I created an example on the [README ](https://github.com/sergiotocalini/virbix#usage)file on how to test the script, can you please be more specific and show what is the error?
Regards,
Sergio
