### ISSUE TITLE
Template does not load. Zabbix 4.0.18.

### ISSUE THREAD

**Issue by darksmoke** [sergiotocalini/virbix#12]
I am trying to load a template but I have an error

Details Import failed

    Cannot read XML: (41) Specification mandate value for attribute data-pjax-transient [Line: 50 | Column: 90].

Zabbix 4.0.18.

**Comment by sergiotocalini** [comment]
Hi @darksmoke,
Indeed, the template has been only used on 3.4. You may need to adjust to the newer versions, I don't have a zabbix installation with 4.0.18.
Regards,
Sergio
