### ISSUE TITLE
Used space: 0B

### ISSUE THREAD

**Issue by JSkolnik** [sergiotocalini/virbix#14]
What's wrong - Zabbix server shows me:
Used space: 0B
Free space: 0B

What should I look at?

**Comment by sergiotocalini** [comment]
Hi @JSkolnik,

It can happen because your pool is not returning the right information.
Please check with the following commands where your virsh is running:

```
~$ zabbix -t "virbix[pool_check, {#POOLUUID}, size_used]"
~$ /etc/zabbix/scripts/agentd/virbix/virbix.sh -s "pool_check" -a p="{#POOLUUID}" -a p="size_used"
~$ virsh pool-info {#POOLUUID}
```

Replace the {#POOLUUID} with the pool-id you want to gather the information.

Best,
Sergio
