### ISSUE TITLE
Debian 10 deploy_zabbix.sh

### ISSUE THREAD

**Issue by egophil** [sergiotocalini/virbix#2]
Hi,

I have debian 10 running. The deploy_zabbix.sh script will fail in line number 11.
Debian 10 uses:
/etc/zabbix//zabbix_agentd.conf.d/
instead of:
/etc/zabbix/zabbix_agentd.d/ 

--- deploy_zabbix.sh	2019-09-02 23:40:04.935621382 +0200
+++ deploy_zabbix.sh.new	2019-09-02 23:40:08.938365913 +0200
@@ -8,5 +8,5 @@
 cp -r ${SOURCE_DIR}/virbix/scripts ${ZABBIX_DIR}/scripts/agentd/virbix/
 cp ${SOURCE_DIR}/virbix/virbix.conf.example ${ZABBIX_DIR}/scripts/agentd/virbix/virbix.conf
 cp ${SOURCE_DIR}/virbix/virbix.sh ${ZABBIX_DIR}/scripts/agentd/virbix/
-cp ${SOURCE_DIR}/virbix/zabbix_agentd.conf ${ZABBIX_DIR}/zabbix_agentd.d/virbix.conf
+cp ${SOURCE_DIR}/virbix/zabbix_agentd.conf ${ZABBIX_DIR}/zabbix_agentd.conf.d/virbix.conf
 sed -i "s|LIBVIRT_DEFAULT_URI=.*|LIBVIRT_DEFAULT_URI=\"${LIBVIRT_URI}\"|g" ${ZABBIX_DIR}/scripts/agentd/virbix/virbix.conf

**Comment by sergiotocalini** [comment]
Hi @egophil 
Thanks for your feedback. I will introduce a new deploy script where you can pass this setting if you need it ;).
Stay updated about this new release.
Regards,
Sergio
