### ISSUE TITLE
Problem on debian 9

### ISSUE THREAD

**Issue by starlessboi** [sergiotocalini/virbix#4]
I just installed according to instruction page, but I get following error for all 3 discovery rule:

Cannot create item: item with the same key "virbix[domain_check, {#DOMUUID}, state]" already exists.

Cannot create item: item with the same key "virbix[net_check, {#NETUUID}, active]" already exists.

Cannot create item: item with the same key "virbix[pool_check, {#POOLUUID}, size_free]" already exists.
Cannot create item: item with the same key "virbix[pool_check, {#POOLUUID}, size_used]" already exists.
Cannot create item: item with the same key "virbix[pool_check, {#POOLUUID}, state]" already exists.

can you help me to get it working?
Zabbix version: 4.2
thanks

**Comment by sergiotocalini** [comment]
Hi @starlessboi,
It is saying that you have duplicate UUID for each of them, I will introduce a fix to avoid that ;)
Best,
Sergio

**Comment by max70ph** [comment]
Hi, after a simple deploy on my ubuntu 16.04... i found the same problem... and maybe a solution:
The LANG env variable make the virsh command translate in italian (or somethig else) the output of virsh.
Just added export LANG=en_EN make output of the virsh command ok for later parsing.
