### ISSUE TITLE
I meet issue when use your script,would  you kindly help, thanks!

### ISSUE THREAD

**Issue by tscswcn** [sergiotocalini/virbix#9]
I meet issue when use your script,would  you kindly help, thanks!

[root@ip-10-120-204-215 virbix]# sh virbix.sh
ZBX_NOTSUPPORTED

env:
zabbix-agent v5
zabbix-server V5
centos 8

**Comment by tscswcn** [comment]
ok, I  receive your reply with emil,  thx!

**Comment by sergiotocalini** [comment]
I've introduced some changes on the main script and also on the deploy script. Please take into account to execute the deploy_zabbix script to properly setup this with zabbix. Also now, if you execute with no parameters should show you this execution example:
./virbix.sh -s domain_list
